fix: Handle access_token with socket.io
leam-tech/renovation_core pull request #52
Opened 2021-01-20 07:51 UTC by assemmarwan

## Problem

Socket.io was failing to connect when the authorization header contained access_token. This is because of the previous implementation of JWTToken in which a JWT token was decoded to extract the user which is not the case anymore.

## Solution

The solution lies in two places:

socketio.js => Replace the authorization header type from JWTToken -> Bearer
realtime.py => Remove JWT decoding and validate using frappe's validate_auth if token is passed, otherwise set the user in frappe.session.user

2021-01-20 08:05 UTC, e-lobo commented on socketio.js
>              query.token = getJwtToken(socket);
This function may need to be changed to => `getJwtToken(socket)`

2021-01-21 10:25 UTC, assemmarwan commented on socketio.js
>              query.token = getJwtToken(socket);
Updated

2021-01-25 07:41 UTC, assemmarwan commented on socketio.js
>              query.token = getJwtToken(socket);
There was actually no need to modify this, I have reverted

2021-01-27 09:27 UTC, faztp12 commented on socketio.js
>              query.token = getJwtToken(socket);
@assemmarwan wont we have to modify the `getJwtToken` function itself ?

2021-01-27 09:28 UTC, faztp12 requested changes
@assemmarwan wont we have to modify the `getJwtToken` function itself ?

2021-01-27 10:22 UTC, assemmarwan commented
@faztp12 I don't think so, because the authorization header from the socket contains `JWTToken` as the type (Because the frontend application sends it). And then we extract the authorization value, which in this case, is the access_token.

2021-01-27 11:31 UTC, faztp12 commented
@assemmarwan but soon, there are going to be clients sending in `Authorization: Bearer <>` after a renovation-core update right ?
Best to have it handled here now itself ?

2021-01-28 05:34 UTC, faztp12 approved these changes

2021-01-28 05:45 UTC, merged