Translations ( with context ) Simple CRUD UI
leam-tech/renovation_core pull request #77
Opened 2021-10-18 09:22 UTC by e-lobo

1. Add new page Renovation Translation Tool.. ( accessible by http://0.0.0.0:8000/app/renovation_translation_tool ) ✅ 
2. Read existing translations ✅ 
3. Create New translation ✅ 
4. Edit existing translations ✅ 
5. Delete a translation ✅ 
6. Docs ✅

2021-11-02 02:14 UTC, fahimalizain commented
@assemmarwan @e-lobo should we sort this based on the language code rather than the name of the language ? It's hard to find Arabic lol 😄 

![image](https://user-images.githubusercontent.com/12441615/139775669-e0ad2d79-df08-45c7-81c1-99c38198decb.png)

2021-11-02 02:29 UTC, fahimalizain requested changes

2021-11-02 02:29 UTC, fahimalizain commented on renovation_core/renovation_core/page/renovation_translation_tool/renovation_translation_tool.js
> +         key:doctype:name
@e-lobo please update to include `*`

2021-11-02 02:29 UTC, fahimalizain commented on renovation_core/renovation_core/page/renovation_translation_tool/renovation_translation_tool.js
> +                page: "renovation_translation_tool",
🔥 🔥

2021-11-02 02:29 UTC, fahimalizain commented on renovation_core/renovation_core/page/renovation_translation_tool/renovation_translation_tool.py
> +            WHEN 2 THEN SUBSTR(context, LOCATE(':', context, 8) + 1,
🔥 🔥 🔥 
Documentation for this magic would be nice for anyone reading this in the future 😄

2021-11-02 06:45 UTC, e-lobo commented on renovation_core/renovation_core/page/renovation_translation_tool/renovation_translation_tool.py
> +            WHEN 2 THEN SUBSTR(context, LOCATE(':', context, 8) + 1,
> uld we sort this based on t

refactored 👍

2021-11-02 06:45 UTC, e-lobo commented
> @assemmarwan @e-lobo should we sort this based on the language code rather than the name of the language ? It's hard to find Arabic lol 😄
> 
> ![image](https://user-images.githubusercontent.com/12441615/139775669-e0ad2d79-df08-45c7-81c1-99c38198decb.png)

refactored 👍

2021-11-02 06:45 UTC, e-lobo commented on renovation_core/renovation_core/page/renovation_translation_tool/renovation_translation_tool.py
> +            WHEN 2 THEN SUBSTR(context, LOCATE(':', context, 8) + 1,
done 👍

2021-11-02 06:46 UTC, e-lobo commented on renovation_core/renovation_core/page/renovation_translation_tool/renovation_translation_tool.js
> +         key:doctype:name
done 👍

2021-11-02 07:37 UTC, fahimalizain approved these changes
All Good 👍🏼 
Fix the XSS issue if you feel like 😄

2021-11-03 12:20 UTC, assemmarwan approved these changes

2021-11-03 12:21 UTC, merged